### ISSUE TITLE
WebKitGTK+ Support

### ISSUE THREAD

**Issue by hamishmack** [faylang/fay#161]
We should make an alternative implementation of the Fay FFI that uses https://patch-tag.com/r/hamish/webkit/home and https://github.com/wavewave/webkit-javascriptcore to interact with WebKitGTK+ 

When compiling Fay code with the Fay compiler things would stay the same as they are now, but with the alternative FFI you could also use your Fay code in...

* GHC compiled native executable with a WebKitGTK+ front end
* GHCi and WebKitGTK+
* GHCJS and web browser (once the GHCJS versions of webkit-javascriptcore functions are implemented)

Here is an example of how to call WebKitGTK+ and javascript core
https://github.com/wavewave/ghcjs-examples/blob/master/ghcjs-hello2/src/Main.hs

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
