### ISSUE TITLE
Generate a better DOM interface from WebKit IDL files

### ISSUE THREAD

**Issue by hamishmack** [faylang/fay#162]
I think we could modify https://github.com/ghcjs/domconv-webkit to also generate Fay functions that use Fay ffi calls to manipulate the DOM.

Currently there are two generators
* **domconv-webkit** creates the Haskell functions that call the WebKitGTK+ C functions (used in the WebKitGTK+ Haskell bindings)
* **domconv-webkit-js** creates GHCJS JavaScript replacement functions for the WebKitGTK+ C functions (these work on any browser not just WebKit)

Both are run like this
````bash
domconv-webkit webkit.idl -I/home/hamish/build/webkit-1.10.0/Source/WebCore
````
Where webkit.idl is from https://patch-tag.com/r/hamish/webkit/home and /home/hamish/build/webkit-1.10.0 is the location of the WebKitGTK+ source code.

A Fay generator would probably be closer to the domconv-webkit than domconv-webkit-js.

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
