### ISSUE TITLE
Is there some way to add templating support to Fay?

### ISSUE THREAD

**Issue by qrilka** [faylang/fay#218]
I have looked through fay examples and everywhere I see manual DOM construction/manipulation e.g. here - https://github.com/faylang/fay-server/blob/master/src/Client.hs#L103
For relatively small application it is OK, but for large UIs I think it would be very cumbersome. Using some kind of templating would be more convenient.
At the moment I find Ember.js appoach (except that it is in js) quite good - it is very easy (at least for me) to see where the data comes from into HTML and what handlers will be called for buttons etc.
In fay-server I see ReactiveMVC module (which could help in reproducing some functionality of Ember.js in Fay though not about templating) but I could not find any example of its usage.
BTW I'm filing this issue (mainly a question for discussion) because I did not find anything like mailing list or google group about Fay.

**Comment by bergmark** [comment]
Spring cleaning. This is too vague to belong on the tracker.

**Comment by perglr** [comment]
FRP in Fay would be very nice -- something like https://github.com/Matt-Esch/virtual-dom
