### ISSUE TITLE
unreliable usage of foreign modules

### ISSUE THREAD

**Issue by qnikst** [faylang/fay#228]
Current solution of modules loading doesn't work reliably if any of --datadir, --datasubdir options is set, and in many other cases. 

Correct solution should consists of a next step Fay Compiler shouldn't generate path on it's own (however default generation option may exists), but user should provide a path to share (or other folder) or FayModuleConfig. To do so enduser library should use next code:

````
module Fay.MegaModule ( datadir, ...)
  where
import Fay_MemaModule_paths (datadir)
````
it could be any other config file with some other defaults.

**Comment by bergmark** [comment]
Spring cleaning. I don't really understand what this is about.
