### ISSUE TITLE
fay preprocessor

### ISSUE THREAD

**Issue by stepcut** [faylang/fay#254]
Hello,

I have code working so that I can use hsx2hs with Fay to allow inline html markup. So now I can do stuff like:

```haskell
       html <- <tr>
                <td class="peg">
                 <span class=(pegColor peg1)></span>
                 <span class=(pegColor peg2)></span>
                 <span class=(pegColor peg3)></span>
                 <span class=(pegColor peg4)></span>
                 <span class=(scoreColor score1)></span>
                 <span class=(scoreColor score2)></span>
                 <span class=(scoreColor score3)></span>
                 <span class=(scoreColor score4)></span>
                </td>
               </tr>
       jq <- renderHTML html
       row0 <- select "#row0"
       after jq row0
```

But, now I need to way to ensure the preprocessor gets run before fay sees the code. 
I could name the files with markup something like Foo.hsx and then use a Makefile (yuck) or a crazy Setup.hs (boo) to run the preprocessor and generate a normal .hs file. But that is troublesome because I would need to trace the dependencies and make sure all the .hsx files get converted. Plus it screws up interaction with GHCi.

In GHC the solution is to put this at the top of the files:

```
{-# OPTIONS_GHC -F -pgmFhs2hsx #-}
```

which tells GHC to run the preprocessor on that file first, and then compile the resulting file.

Would be nice if I could do:

```
{-# OPTIONS_FAY -F -pgmFhs2hsx #-}
```

as well. That would automatically pass the source code through hsx2hs, output it to a new temp file, compile it with fay, and then delete the temp file.

Any thoughts?
- jeremy

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
