### ISSUE TITLE
Precendence issue when creating a new fay object

### ISSUE THREAD

**Issue by exlevan** [faylang/fay#283]
The following definition of new:
```haskell
new :: a -> Fay b
new = ffi "new %1()"
```
does not produce a code that creates an object from supplied constructor.  This happens because `%1` expands to a call to `fayToJs` in the generated code, and the resulting javascript looks like this:
```javascript
new Fay$$fayToJs(["user","AppView",[]],$p1)()
```
Since the new operator has a precendence over the function application, the result of evaluating this is creation of a new `fayToJs` object, which is then applied to an empty argument list.

The problem can be worked around by placing the argument in the parentheses:
```haskell
new = ffi "new (%1)()"
```

But the better fix might be to place all fay arguments in the parentheses implicitly, which will prevent the precendence issues.

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
. Ptr or an empty data decl is needed for this.
