### ISSUE TITLE
Record info doesn't pay attention to imports / export

### ISSUE THREAD

**Issue by mgsloan** [faylang/fay#289]
Here's an example:

```haskell
module A where

data Foo = Foo { foo :: Int }
```

```haskell
module B where

data Foo = Foo { bar :: Int }
```

```haskell
{-# LANGUAGE RecordWildCards #-}

module C where

import A
import B ()

test = Foo {..}
  where
    foo = 1
```

The generated javascript contains:
```javascript
var C$test = new Fay$$$(function(){
  var foo = 1;
  return (function(){
    var Foo = new $_A$Foo();
    Foo.bar = bar;
    return Foo;
  })();
});
```
(Note that `bar` was used instead of `foo` for the field)

I looked into this issue a bit, to see if there's an easy resolution.  I couldn't see a straightforward one, but it seems like the right type is resolved - maybe the `InitialPass` needs to store information about fully qualified names.   In particular, [the following](https://github.com/faylang/fay/blob/d10004884c78451aa94e1ac277a7795ad54ad0c3/src/Fay/Compiler/InitialPass.hs#L29) doesn't hold when you take into account import / export hiding:

```haskell
              -- Merges the state gotten from passing through an imported
              -- module with the current state. We can assume no duplicate
              -- records exist since GHC would pick that up.
```

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, and i think this has been fixed since we started using haskell-names.
