### ISSUE TITLE
ability to walk the JS/JSON structure instead of converting it to records

### ISSUE THREAD

**Issue by emmanueltouzery** [faylang/fay#315]
I may have missed this in the Fay documentation...

I have a JSON from the server, which in fact is a configuration file. As such, it doesn't follow a record format and it's more using the JS objects as key-value, and I know the keys ahead of time.

Ideally what I would like would be an API like Aeson's "Value" API:

http://hackage.haskell.org/packages/archive/aeson/0.6.1.0/doc/html/Data-Aeson.html#t:Value

That allows you to walk the structure... For instance you treat the object as a `Map String Value`, value can be a Array, and so on.

am I missing something, or this is impossible in Fay? The only related documentation I can find is there:
https://github.com/faylang/fay/wiki/Foreign-function-interface

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
