### ISSUE TITLE
Implement language-typescript.

### ISSUE THREAD

**Issue by tomlokhorst** [faylang/fay#328]
[TypeScript](http://www.typescriptlang.org/) is a typed superset of JavaScript, with a well defined [specification](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf).

In relation to Fay, there are several applications:

 - Use TypeScript definition files to generate Fay bindings to existing JavaScript libraries. [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) is an active community of people creating type definitions, it would be useful to automatically generate Fay bindings from those.
 - Generate TypeScript definition files for Fay programs, so TypeScript users can access Fay libraries in a typed way.

These are interesting applications, and there might even be more, but they rely on being able to read and/or write TypeScript from Haskell.
A `language-typescript` library could be build as a full implementation of the TypeScript AST. However a `language-typescript-defintions` library, just for handling the "types" part of TypeScript, would also be useful.

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen. language-typescript exists now for the record.
