### ISSUE TITLE
Multiple input files and -o clobbers the output

### ISSUE THREAD

**Issue by kfish** [faylang/fay#347]
I would like to structure my Haskell code in separate files (one file per module, as Haskell requires), but generate one output javascript file.

Currently, if I use a commandline like:

    fay --package fay-text -o output.js Foo.hs Bar.hs

then fay will:

  1. compile Foo.hs, writing the result to output.js
  2. compile Bar.hs, overwriting output.js

So -o cannot be used with multiple files.

If I instead use multiple invocations:

    fay --package fay-text Foo.hs
    fay --package fay-text Bar.hs

then the resulting Foo.js and Bar.js will contain redundant copies of the same code (RTS, stdlib and fay-text library code). If I build with --no-stdlib --library, then I still get redundant copies of fay-text.

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen. Use a top level module.
