### ISSUE TITLE
Macro generation of ffi strings

### ISSUE THREAD

**Issue by kfish** [faylang/fay#352]
(I know this sounds ugly but)

I'd like to clean up multiline ffi statements, which I'm using to generate code in the format that angularjs expects. The body of an ffi statement must be a String literal (not an expression that evaluates to String), so we can't use Haskell functions to build it up from Fay user code.

As a motivating example, I'd like to be able to make a macro to replace:

    replace_field(o, old, new)

with:

    "if (old in o) { o[new] = o[old]; delete o[old]; };"

Possibilities:

  * allow LANGUAGE CPP for #define macros.
  * extend ffiExp to handle simple expressions to generate a String, not just (Lit _ (String ...))

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
