### ISSUE TITLE
Add a `--pretty-operators` flag

### ISSUE THREAD

**Issue by bergmark** [faylang/fay#366]
This flag would disable the name munging of all top level operators.

Instead of generating `Prelude.$36$`, generate `Prelude['$']` and so on. This would make debugging easier.

For production this should probably not be used since closure doesn't rename anything in brackets, hence a new flag for it.

**Comment by michalseweryn** [comment]
I made pull request, any suggestions?

**Comment by bergmark** [comment]
Thanks for the reminder, I'll take a look now!

**Comment by michalseweryn** [comment]
This issue should be closed.

**Comment by bergmark** [comment]
thanks
