### ISSUE TITLE
Callback feature request

### ISSUE THREAD

**Issue by dluciv** [faylang/fay#414]
I could miss something.

Fay provides excellent *ffi* to access foreign functions. Results of all of them are then wrapped into `Fay` monad and everything looks just the same as for Haskell. But...

This all works well for blocking API calls, while JavaScript itself often relies on continuation passing style that it alike Haskell's one except callback invokation order. Genuine Haskell invokes blocking POSIX (and so on) API and it looks as a pain (Haskell looks too advanced for such a legacy environment). JavaScript asynchroneous APIs do look much more natural to be integrated with Haskell.

For Fay (and for any other Haskell-JavaScript compiler too) it is very sad to use API in following way (excample from `fay-dom` source):

    setReadyStateHandler :: (XMLHttpRequest -> Fay ()) -> XMLHttpRequest -> Fay XMLHttpRequest

For Haskell it could be much more natural to write:

    do
      ...
      Just result <- sendXmlHttpRequest ... params ...
      ...

There are a lot of other examples surely. At least, all Node.js input is handled similarly. [Here](https://gist.github.com/paulcc/4157816) is what can be done. But why we need palying with `Cont` monad and in the same time having `Fay` monad already handling the callbacks (just because it is a monad)?..

Can we upgrade *ffi* and `Fay` `>>=` operator in some way to make this built-infeature and reduce such an overhead?

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity, it's unlikely that this will happen.
