### ISSUE TITLE
problems with cabal-sandbox in windows

### ISSUE THREAD

**Issue by CarstenKoenig** [faylang/fay#420]
I tried installing fay and fay-base into a local sandbox under windows.
When I try to compile a simple file using fay I always get this (when giving the absolute path to the `x...-packages.conf.d`):

    fay.exe: ghc: <command line>: cannot satisfy -package fay-base-0.19.4.1:
        fay-base-0.19.4.1-985fcb829f3541d3d885d378bc2c898f is unusable due to missing or recursive dependencies:
          fay-0.21.2.1-5f3f88230341a60e39daf9c3eb15daac
        (use -v for more information)

When I look into the packages both libs with the correct version are there.

The same situation under Linux: everything works, so I guess it's some strange windows/path issue?

**Comment by bergmark** [comment]
Spring cleaning. Lack of activity.
