### ISSUE TITLE
Use FFI for JQuery Validation plugin

### ISSUE THREAD

**Issue by denisshevchenko** [faylang/fay#427]
Hello!

I try to use Fay with JQuery Validation plugin in my Yesod-project. So I write:

```haskell
validateForm :: JQuery -> Fay ()
validateForm = do
    ffi "%1.validate({rules:{newUserEmail:{required:true,email:true}},messages:{newUserEmail:{required: \"Insert your email, please\",email: \"Invalid email\"}}})"

...

main :: Fay ()
main = ready $ do
    select "#registerNewUserForm" >>= validateForm
    return ()
```

And it works fine. But I cannot add parameter for FFI-string. For example, I try this:

```haskell
validateForm :: Text -> JQuery -> Fay ()
validateForm = do
    ffi "%2.validate({rules:{%1:{required:true,email:true}},messages:{%1:{required: \"Insert your email, please\",email: \"Invalid email\"}}})"

...

main :: Fay ()
main = ready $ do
    select "#registerNewUserForm" >>= validateForm "newUserEmail"
    return ()
```

In this case I got error:

```bash
fay: templates/home/register/form/Form.hs: (11,1)-(11,13):
invalid JavaScript code in FFI format string:
"validateForm" (line 1, column 139):
unexpected "("
expecting letter or digit or ":"
in ...
```

How can I fix it?

**Comment by bergmark** [comment]
We parse FFI expressions using language-ecmascript meaning they need to be a valid javascript expression **before** the interpolation to replace the `%` arguments occur.

Keys in JS objects need to be valid identifiers or numbers, to add a dynamic property to them you must assign it with `o[key] = value`. Even so, you are trying to set the key to a JQuery object which would result in the key becoming something like `"[Object]"`. I don't recall the API of jquery-validate, but perhaps you are intending it to be a selector string?

A side note: I had to think for a moment to figure out why the first example works! FFI declarations need the type signature immediately surrounding it, `f :: X; f = ffi "..."` (without `do`) in a top-level declaration or `ffi "..." :: x` if it's an internal expression. It seems like the compiler's desugaring phase is accidentally ordered so the redundant do in your first example is removed before ffi desugaring occurs!

**Comment by denisshevchenko** [comment]
Do you mean I must write like this?

```haskell
validateForm :: Text -> JQuery -> Fay ()
validateForm = do
    ffi "(function() { var o = {}; o['field'] = %1; %2.validate({rules:{o['field']:{required:true,email:true}},messages:{o['field']:{required: \"Insert your email, please\",email: \"Invalid email\"}}}) })"
```

**Comment by bergmark** [comment]
That is also not valid javascript, keys in object literals cannot be dynamic. You probably want something like this:
```
"var myRules = {}; \
myRules[%1] = {required:true,email:true}; \
[...]
%2.validate({rules: myRules, [...]})
```

**Comment by denisshevchenko** [comment]
Thank you very much! It works now.

**Comment by bergmark** [comment]
Glad to hear it, you're welcome!
