### ISSUE TITLE
fay doesn't compile with ghc 8.0.1

### ISSUE THREAD

**Issue by henrylaxen** [faylang/fay#441]
I tried raising some deps, namely
+      base >= 4.5 && < 4.10
+    , process >= 1.1 && < 1.5
+    , time >= 1.4 && < 1.7
and I had to recompile type-eq and raise its base dep as well, but it still exited with:

fay-0.23.1.12: installed package info from too old version of Cabal (key field
does not match id field)

I'm using:

cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 

Best wishes,
Henry Laxen

**Comment by henrylaxen** [comment]
my mistake.  I forgot to remove the dist directory.  After doing so, it does compile with the above changes to the dependencies.  Congratulations.

**Comment by bergmark** [comment]
I opened https://github.com/glaebhoerl/type-eq/pull/7, nice to see there's only one dependency remaining
